import "@/styles/globals.css";
import type { Metadata } from "next";
import { Providers } from "@/components/Providers/Providers";

export const metadata: Metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
};

interface RootLayoutProps {
	children: React.ReactNode;
}

export default function RootLayout({ children }: RootLayoutProps) {
	return (
		<html lang="en">
				<body className="min-h-screen bg-gray-900">
					<Providers>
						{children}
					</Providers>
				</body>
		</html>
	);
}
